# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.enter_name_lbl = QtWidgets.QLabel(Dialog)
        self.enter_name_lbl.setObjectName("enter_name_lbl")
        self.gridLayout.addWidget(self.enter_name_lbl, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_name_txt = QtWidgets.QLineEdit(Dialog)
        self.project_name_txt.setMinimumSize(QtCore.QSize(200, 40))
        self.project_name_txt.setObjectName("project_name_txt")
        self.horizontalLayout.addWidget(self.project_name_txt)
        self.done_enter_name_btn = QtWidgets.QPushButton(Dialog)
        self.done_enter_name_btn.setMinimumSize(QtCore.QSize(60, 40))
        self.done_enter_name_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/确定.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.done_enter_name_btn.setIcon(icon1)
        self.done_enter_name_btn.setIconSize(QtCore.QSize(40, 25))
        self.done_enter_name_btn.setObjectName("done_enter_name_btn")
        self.horizontalLayout.addWidget(self.done_enter_name_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "项目名称"))
        self.enter_name_lbl.setText(_translate("Dialog", "名称已存在！"))
        self.project_name_txt.setPlaceholderText(_translate("Dialog", "项目名称"))
